# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 202)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_converter = QtWidgets.QFrame(self.centralwidget)
        self.frame_converter.setGeometry(QtCore.QRect(0, 0, 391, 201))
        self.frame_converter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_converter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_converter.setObjectName("frame_converter")
        self.label_2 = QtWidgets.QLabel(self.frame_converter)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_converter = QtWidgets.QPushButton(self.frame_converter)
        self.pushButton_converter.setGeometry(QtCore.QRect(120, 140, 151, 41))
        self.pushButton_converter.setObjectName("pushButton_converter")
        self.label_console = QtWidgets.QLabel(self.frame_converter)
        self.label_console.setGeometry(QtCore.QRect(0, 179, 391, 21))
        self.label_console.setStyleSheet("")
        self.label_console.setAlignment(QtCore.Qt.AlignCenter)
        self.label_console.setObjectName("label_console")
        self.lineEdit_local_final = QtWidgets.QLineEdit(self.frame_converter)
        self.lineEdit_local_final.setGeometry(QtCore.QRect(10, 100, 181, 31))
        self.lineEdit_local_final.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_local_final.setObjectName("lineEdit_local_final")
        self.lineEdit_local = QtWidgets.QLineEdit(self.frame_converter)
        self.lineEdit_local.setGeometry(QtCore.QRect(10, 60, 371, 31))
        self.lineEdit_local.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_local.setObjectName("lineEdit_local")
        self.comboBox_tipo = QtWidgets.QComboBox(self.frame_converter)
        self.comboBox_tipo.setGeometry(QtCore.QRect(110, 30, 171, 22))
        self.comboBox_tipo.setObjectName("comboBox_tipo")
        self.pushButton_contato = QtWidgets.QPushButton(self.frame_converter)
        self.pushButton_contato.setGeometry(QtCore.QRect(290, 30, 91, 21))
        self.pushButton_contato.setObjectName("pushButton_contato")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_converter)
        self.lineEdit.setGeometry(QtCore.QRect(200, 100, 181, 31))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_desktop = QtWidgets.QPushButton(self.frame_converter)
        self.pushButton_desktop.setGeometry(QtCore.QRect(10, 140, 75, 21))
        self.pushButton_desktop.setObjectName("pushButton_desktop")
        self.label = QtWidgets.QLabel(self.frame_converter)
        self.label.setGeometry(QtCore.QRect(0, -1, 391, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame_converter)
        self.label_3.setGeometry(QtCore.QRect(360, 180, 31, 20))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Tipo de Conversão"))
        self.pushButton_converter.setText(_translate("MainWindow", "Converter"))
        self.label_console.setText(_translate("MainWindow", "console"))
        self.lineEdit_local_final.setPlaceholderText(_translate("MainWindow", "Local do Arquivo Final"))
        self.lineEdit_local.setPlaceholderText(_translate("MainWindow", "Local do Arquivo"))
        self.pushButton_contato.setText(_translate("MainWindow", "Sobre"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "nomeDoArquivoFinal"))
        self.pushButton_desktop.setText(_translate("MainWindow", "Desktop"))
        self.label.setText(_translate("MainWindow", "CSV to XLSX"))
        self.label_3.setText(_translate("MainWindow", "v1.0"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())